Failed step gutter icon
SpecFlowOSS/SpecFlow.Rider pull request #101
Opened 2021-05-05 13:39 UTC by Socolin

2021-05-06 09:34 UTC, nemesv requested changes

2021-05-06 09:34 UTC, nemesv commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Utils/TestOutput/OutputTestParser.cs
> +            var colonIndex = statusLine.IndexOf(':');
The error message is not correctly parsed if it contains a "colon".

This is a step output message using MSTest:
```
And my total score should be 120
-> error: Assert.AreEqual failed. Expected:<120>. Actual:<29>.  (0.0s)
```

But in the tooltip the `<` after the colons are truncated:
![image](https://user-images.githubusercontent.com/251330/117275978-e362e480-ae5e-11eb-8798-2fd0ad970c36.png)

2021-05-09 03:44 UTC, Socolin commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Utils/TestOutput/OutputTestParser.cs
> +            var colonIndex = statusLine.IndexOf(':');
Fixed, `<` was interpreted by the `RichText`

2021-05-09 03:45 UTC, Socolin commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Psi/GherkinKeywordList.cs
> +                .Concat(_translationsPerKeyword["And"])
Fixed

2021-05-10 09:01 UTC, merged