Regex based argument highlighting
SpecFlowOSS/SpecFlow.Rider pull request #35
Opened 2021-03-03 16:20 UTC by alexandrafung

2021-03-04 14:47 UTC, nemesv requested changes

2021-03-04 14:47 UTC, nemesv commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Daemon/ParameterHighlighting/ParameterHighlightingProcessor.cs
> +        public override void VisitNode(ITreeNode node, IHighlightingConsumer consumer)
We don't need to derive from the `TreeNodeVisitor<IHighlightingConsumer>` here, so we can make the VisitNode private and we also don't need to invoke it over the `GherkinStep`

2021-03-05 07:10 UTC, alexandrafung commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Psi/GherkinPsiUtil.cs
> +            var stepTextWithKeyword = step.GetStepText(true);
We need to generate again the full step because after the keyword the step can begin with whitespaces and for the highlighting, we need the full length with the whitespaces. If we would get only the keyword, we would lose the whitespaces.

2021-03-05 07:20 UTC, alexandrafung commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Daemon/ParameterHighlighting/ParameterHighlightingProcessor.cs
> +        public ParameterHighlightingProcessor(IDaemonProcess daemonProcess, ResolveHighlighterRegistrar resolveHighlighterRegistrar)
I removed them.

2021-03-05 07:21 UTC, alexandrafung commented on src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Daemon/ParameterHighlighting/ParameterHighlightingProcessor.cs
> +        public override void VisitNode(ITreeNode node, IHighlightingConsumer consumer)
Thanks for fixing it.

2021-03-05 07:24 UTC, nemesv approved these changes

2021-03-05 07:38 UTC, merged